### ISSUE TITLE
Crash due to null document

### ISSUE THREAD

**Issue by MB3hel** [MB3hel/CFModDownloader#1]
```
Traceback (most recent call last):
  File "cfmparse.py", line 114, in <module>
  File "mpparser.py", line 103, in parse
  File "selenium\webdriver\remote\webdriver.py", line 932, in page_source
  File "selenium\webdriver\remote\webdriver.py", line 430, in execute
  File "selenium\webdriver\remote\errorhandler.py", line 247, in check_response
selenium.common.exceptions.WebDriverException: Message: TypeError: this.document.documentElement is null
Stacktrace:
getPageSource@chrome://remote/content/marionette/actors/MarionetteCommandsChild.jsm:349:5
receiveMessage@chrome://remote/content/marionette/actors/MarionetteCommandsChild.jsm:126:31

[2556] Failed to execute script 'cfmparse' due to unhandled exception!
Traceback (most recent call last):
  File "C:\Users\mbehe\Projects\CFModpackImporter/src\importer.py", line 203, in do_generate
    raise Exception("Parsing modpack failed.")
```

Likely need a check before accessing page source

**Comment by MB3hel** [comment]
Seems to only affect firefox and is intermittent. Likely the tabs are opened "too fast" and one is checked while new tab page is still present in tab
